from enum import Enum

class ReportId(Enum):
    REDEMPTION_ACCOUNT = 2
    MONEY_SPENT = 3
    MONEY_DEPOSITED = 4
    RECOGNITION_DETAILS = 5
    POINTS_REDEEMED = 6
    RECOGNITION_STATUS = 7
    USERS = 9
    LOGIN = 10
    POINT_TRANSACTIONS = 11
    POINT_BUDGETS = 12
    CLIENT_FULFILLMENT = 14
    FUNDING_RECONCILIATION = 15
    RECOGNITION_PROGRAM_UTILIZATION = 16
    USER_POINT_BALANCE = 18
    REDEMPTION_POINT_SOURCE_FIFO = 21